config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "fastings#index"
  resources :fastings, only: [:create, :destroy]
  resources :memos, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fasting.rb
class Fasting < ApplicationRecord

  # belongs_to :user

  validates :body_weight, presence: true
  validates :motion_id, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :motion
  belongs_to :motion_time

end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男性' },
    { id: 3, name: '女性' },
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/memo.rb
class Memo < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :number_meals
end

app/models/motion.rb
class Motion < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'できていない' },
    { id: 3, name: '散歩' },
    { id: 4, name: 'ジョギング' },
    { id: 5, name: 'スポーツ' },
    { id: 6, name: 'ストレッチ' },
    { id: 7, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :fastings
end

app/models/motion_time.rb
class MotionTime < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '10分' },
    { id: 3, name: '10~30分' },
    { id: 4, name: '30分~1時間' },
    { id: 5, name: '1時間~1時間30分' },
    { id: 6, name: '2時間以内' },
    { id: 7, name: '2時間以上' }
  ]
  include ActiveHash::Associations
  has_many :fastings
end

app/models/number_meals.rb
class NumberMeals < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '0回' },
    { id: 3, name: '1回' },
    { id: 4, name: '2回' },
    { id: 5, name: '3回' },
    { id: 6, name: '4回' },
    { id: 7, name: '4回以上' }
  ]
  include ActiveHash::Associations
  has_many :memos
end

app/models/user.rb
class User < ApplicationRecord

  # has_many :fastings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
  validates :nickname, presence: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :gender_id, :target_body_weight])
  end
end

app/controllers/fastings_controller.rb
class FastingsController < ApplicationController

  def index
    @fastings = Fasting.all
    @personal = Fasting.last
    @fasting = Fasting.new
    @memos = Memo.all
    @memo = Memo.new
  end

  def create
    fasting = Fasting.new(fasting_params)
    if fasting.save
      redirect_to root_path
    else
      render :index
    end
  end

  def destroy
    fasting = Fasting.find(params[:id])
    fasting.destroy
    redirect_to root_path
  end

  private

  def fasting_params
    params.require(:fasting).permit(:body_weight, :motion_id, :motion_time_id)
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def create
    memo = Memo.new(memo_params)
    if memo.present?
      memo.save
      redirect_to root_path
    else
      render :index
    end
  end

  private

  def memo_params
    params.require(:memo).permit(:number_meals_id, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fastings_helper.rb
module FastingsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/fastings/_personal.html.erb
<div class="log">
  <div class='pulldown'>
    
    <div class="log-date">
      <!-- 記録した時刻を出力する -->
      <%= fasting.created_at.to_s(:datetime_jp) %>
    </div>

    <%= link_to '削除', fasting_path(fasting), class: 'delete', method: :delete %>
      
  </div>

  <div class="log-content">

    <!-- 記録内容を記述する -->
    <span class='weight'>体重:</span><%= fasting.body_weight %>kg

    <span class='fitness'>運動:</span><%= fasting.motion.name %>

    <% unless fasting.motion_id == 2 %>
      を<%= fasting.motion_time.name %>！
    <% end %>
  </div>

</div>

app/views/fastings/index.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>fasting-balance</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ここにサイト説明を入れます">
    <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/fixmenu_pagetop.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
    $(function(){
    $('a[href^="#"]').click(function() {
    var speed = 800;
    var href= $(this).attr("href");
    var target = $(href == "#" || href == "" ? 'html' : href);
    var position = target.offset().top;
    $('body,html').animate({scrollTop:position}, speed, 'swing');
    return false;
    });
    });
    </script>
  </head>

  <body>

    <header>
    <%# <a href="index.html"><img src="/assets/logo.png" alt="SAMPLE COMPANY"></a> %>
      <h1 id="logo"><%= image_tag asset_path("logo.png") %></h1>
      <nav id="menubar">
        <div class='new-record'>
          <% if @personal %>
            <span class='memory-title'>前回の記録</span>
            <div class='memory'>
              <div class='end-date'>
                <%= @personal.created_at.to_s(:datetime_jp) %>
              </div>
              <span class='weight'>体重:</span><%= @personal.body_weight %>kg
              <span class='fitness'>運動:</span><%= @personal.motion.name %>
              <% unless @personal.motion_id == 2 %>
                を<%= @personal.motion_time.name %>！
              <% end %>
            </div>
          <% end %>
        </div>

        <ul>
          <% if user_signed_in? %>
            <li><a href="#new">ログアウト</a></li>
          <% else %>
            <li><a href="#new">新規 & ログイン</a></li>
          <% end %>
          <li><a href="#company">概要</a></li>
          <li><a href="#service">測定・記録</a></li>
          <li><a href="#contact">メモ</a></li>
        </ul>
      </nav>
    </header>

    <div id="container">

      <div id="contents">

        <section id="new">

          <% if user_signed_in? %>
             <h2>ログアウト</h2>
          <% else %>
            <h2>新規登録・ログイン</h2>
          <% end %> 

          <% if user_signed_in? %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to '新規登録', new_user_registration_path %>・<%= link_to 'ログイン', new_user_session_path %>
          <% end %>

        </section>
        <!--/#new-->

      <section id="company">

        <h2>概要</h2>

        <h3>FastingBalance概要</h3>
        <table class="ta1">
          <caption>FastingBalanceを使う上で大切なこと</caption>
          <tr>
          <th>FastingBalanceとは？</th>
          <td>このアプリは、「プチ断食」を健康に取り入れるためのサポートアプリです。</td>
          </tr>
          <tr>
          <th>プチ断食とは？</th>
          <td>プチ断食は１日〜１週間何も食べない断食と違い、１日２４時間のうち６時間〜８時間の間は好きな量食べてもいいという断食です。
          要は、１６〜１８時間の間何も食べない時間を作ることです！</td>
          </tr>
          <tr>
          <th>おすすめの食事時間</th>
          <td>ずばり、お昼過ぎから寝る３時間前！具体的にいうと、13時〜19時の間は食べ放題！</td>
          </tr>
          <tr>
          <th>無理はしない</th>
          <td>とは言っても最初はお腹が空いて、仕事や勉学に集中できない！という方がほとんどなので、そこで無理は禁物です。おすすめは、素焼きナッツやヨーグルトなどをよく噛んで食べましょう。個人的には素焼きナッツがいいと思います！</td>
          </tr>
          <tr>
          <th>継続が大切</th>
          <td>ここまで読んで、「あれ、これならできそう！」と思った方！そうなんです。すごく簡単に継続できちゃうんです！ただ気をつけて欲しいのが、継続しないと意味がないということです。このプチ断食に関する論文や書物でも同じことが書かれています。</td>
          </tr>
          <tr>
          <th>プチ断食のデメリット</th>
          <td>デメリットとして上げられるのは、脂肪とともに筋肉量も落ちてしまうこと。すなわち代謝が落ちやすくなるので、散歩なり軽い運動は取り入れましょう！</td>
          </tr>
          <tr>
          <th>プチ断食のメリット</th>
          <td>メリットに関しては、たくさんあり過ぎて書ききれないので、本やYouTubeなどを見てみてください！めんどくさいという方はリンク貼っときますので、こちらからよろしくお願いします！
          </td>
          </tr>
        </table>

        <%= link_to 'プチ断食のメリットはこちらから！', 'https://oceans.tokyo.jp/health/2020-1005-6/' %>

      <section id="service">

      <h2>測定・記録</h2>

      <div class='record-measurement'>
        <div class='parent-measurement'>
          <%= form_with model: @fasting, id: 'fasting', local: true do |f| %>

            <div class='measurement'>
            
              <div class='weight'>
              体重
              </div>
              <%= f.text_field :body_weight, placeholder: "(kg)", id: 'weight' %>

              <div class='fitness'>
              運動
              </div>
              <%= f.collection_select(:motion_id, Motion.all, :id, :name, {}, {id: 'motion'}) %>

              <div class='week_motion'>
              時間
              </div>
              <%= f.collection_select(:motion_time_id, MotionTime.all, :id, :name, {}, {id: 'motion-time'}) %>

              <div>
                <%= f.submit "記録", {class: 'botan', id: 'submit-botan'}%>
              </div>
            </div>

          <% end %>
        </div>

        <div class='record'>
          
          <%= render partial: 'personal', collection: @fastings, as: "fasting" %>

        </div>
      </div>

      </section>
      <!--/#service-->

      <section id="contact">

        <%= render partial: 'memos/memo', locals: {memo: @memo}%>

        <div class='memo-display'>

          <%= render  partial: 'memos/memo_recod', collection: @memos, as: "memos" %>

        </div>

      </section>
      <!--/#contact-->

      </div>
      <!--/#contents-->

    </div>
    <!--/#container-->

    <footer>
    <small>Copyright&copy; <a href="index.html">SAMPLE COMPANY</a> All Rights Reserved.</small>
    <span class="pr">《<a href="https://template-party.com/" target="_blank">Web Design:Template-Party</a>》</span>
    </footer>

    <!--ページの上部に戻る「↑」ボタン-->
    <p class="nav-fix-pos-pagetop"><a href="#">↑</a></p>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FastingBalance1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_memo.html.erb
<h2>メモ</h2>

<%= form_with model: memo, url: memos_path, class: 'memo-form', id: 'memo', local: true do |m| %>

  <div class='number-meals'>
    <div class='eat'>
      食事回数
    </div>
    <%= m.collection_select(:number_meals_id, NumberMeals.all, :id, :name, {}, {class: 'eat-select', id: 'number-meals'}) %>
  </div>
  
  <div class='memo'>
    <div class='memos'>
      メモ
    </div>
    <%= m.text_area :memo, placeholder: "何をどれだけ食べた。", class: 'memo-area', id: 'memo' %>
  </div>

  <div>
    <%= m.submit "メモる", class: 'memo-botan' %>
  </div>

<% end %>

app/views/memos/_memo_recod.erb
<div class='memoreco'>
  <div>
    <span class='memo-name'>食事回数：</span><%= memos.number_meals.name %>
  </div>
  <span class='memo-name'>メモ：</span><%= memos.memo %>
</div>